"use client";
import { useEffect, useState } from "react";
import { PageHeader } from "@/components/layout/PageHeader";
import { CheckCircle2, Clock3, Lightbulb, MessageSquareText, ShieldCheck } from "lucide-react";
import { useAccess } from "@/components/access/AccessProvider";
import type { AccessibleResourcePayload, DDD, ManagedDDD } from "@/types";

export default function DddPage(){
 const {user}=useAccess(); const [available,setAvailable]=useState<DDD[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [id,setId]=useState(""),[answer,setAnswer]=useState<number|null>(null),[confirmed,setConfirmed]=useState(false); const d=available.find(x=>x.id===id)||available[0];
 useEffect(()=>{fetch("/api/ddds").then(async response=>{const payload=await response.json();if(!response.ok)throw new Error(payload.error);const data=payload as AccessibleResourcePayload<DDD>;const saved=localStorage.getItem("capacita-managed-ddds");const published=saved?(JSON.parse(saved) as ManagedDDD[]).filter(item=>item.status==="Publicado"&&(data.all||item.mesa==="Todas as mesas"||data.mesas.includes(item.mesa))&&(item.unidade==="Todas"||item.unidade===user.unidade)&&(item.turno==="Todos"||item.turno===user.turno)):[];const next=[...published,...data.items];setAvailable(next);setId(next[0]?.id||"");}).catch(reason=>setError(reason instanceof Error?reason.message:"Não foi possível carregar os DDDs.")).finally(()=>setLoading(false));},[user]);
 useEffect(()=>{setConfirmed(localStorage.getItem(`capacita-ddd-${id}`)!==null);},[id]);
 function change(v:string){setId(v);setAnswer(null);}
 function confirm(){if(answer===null||!d)return;setConfirmed(true);const receipt={aluno:user.nome,ddd:d.tema,dataHora:new Date().toLocaleString("pt-BR"),resposta:answer,acertou:answer===d.correta,status:"Ciência registrada"};localStorage.setItem(`capacita-ddd-${id}`,JSON.stringify(receipt));localStorage.setItem("capacita-last-ddd",JSON.stringify({nome:d.tema,mesa:d.mesa,data:new Date().toLocaleDateString("pt-BR")}));}
 if(loading)return <div className="card p-8 text-center text-sm text-gray-500">Carregando DDDs autorizados...</div>;if(error||!d)return <div className="card p-8 text-center text-sm text-red-700">{error||"Nenhum DDD disponível."}</div>;
 const managed=d as Partial<ManagedDDD>;
 return <><PageHeader eyebrow="Diálogo Diário de Desempenho" title="DDD do Dia" description="Uma pausa curta para alinhar decisões críticas antes que o turno ganhe velocidade." action={<select className="field w-auto min-w-52" value={id} onChange={e=>change(e.target.value)}>{available.map(x=><option key={x.id} value={x.id}>{x.tema} · {x.mesa}</option>)}</select>}/>
  <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><section className="card overflow-hidden"><div className="bg-forest p-7 text-white"><div className="flex flex-wrap items-center gap-3 text-xs"><span className="rounded-full bg-blush px-3 py-1 font-bold text-forest">DDD publicado</span><span className="flex items-center gap-1 text-white/50"><Clock3 size={14}/>5 minutos</span></div><h2 className="mt-7 text-3xl font-bold">{d.tema}</h2><div className="mt-2 flex flex-wrap gap-x-5 gap-y-1 text-xs text-white/55"><span>Mesa: {d.mesa}</span><span>Data: {managed.data||"28/06/2026"}</span><span>Responsável: {managed.responsavel||"Liderança COA"}</span></div></div><div className="space-y-6 p-6 sm:p-8"><div><p className="eyebrow mb-2">Objetivo</p><p className="text-sm leading-6">{d.objetivo}</p></div><div className="rounded-2xl border border-line bg-slate-100 p-5"><p className="mb-2 flex items-center gap-2 text-xs font-bold text-slate-800"><Lightbulb size={17}/>Ponto de atenção</p><p className="text-sm leading-6 text-slate-900">{d.conteudo}</p></div><div><p className="eyebrow mb-2">Situação prática</p><p className="text-sm leading-6">{d.situacao}</p></div><div><p className="mb-3 text-sm font-bold">{d.pergunta}</p><div className="grid gap-2">{d.alternativas.map((a,i)=><button disabled={confirmed} key={a} onClick={()=>setAnswer(i)} className={`flex items-center gap-3 rounded-xl border p-3 text-left text-sm transition ${answer===i?"border-leaf bg-red-50":"border-line hover:border-leaf/50"}`}><span className={`grid h-7 w-7 place-items-center rounded-full text-xs font-bold ${answer===i?"bg-leaf text-white":"bg-mist"}`}>{String.fromCharCode(65+i)}</span>{a}</button>)}</div></div>{confirmed?<div className="flex items-center gap-3 rounded-xl bg-emerald-50 p-4 text-emerald-800"><CheckCircle2/><div><b className="text-sm">Ciência registrada</b><p className="text-xs">Resposta, data e confirmação registradas para {user.nome}.</p></div></div>:<button disabled={answer===null} onClick={confirm} className="btn-primary w-full py-3"><ShieldCheck size={18}/>Confirmar ciência</button>}</div></section>
  <aside className="space-y-5"><div className="card p-5"><p className="eyebrow">Sua frequência</p><div className="mt-4 flex items-end gap-2"><b className="text-4xl">94%</b><span className="mb-1 text-xs text-emerald-600">+4 p.p.</span></div><p className="mt-2 text-xs text-gray-400">18 de 19 DDDs realizados neste mês.</p><div className="mt-5 grid grid-cols-7 gap-1">{Array.from({length:21}).map((_,i)=><span key={i} className={`aspect-square rounded ${i<18?"bg-leaf":i===18?"bg-amber-300":"bg-line"}`}/>)}</div></div><div className="card p-5"><MessageSquareText className="text-leaf"/><h3 className="mt-5 font-bold">Como funciona?</h3><p className="mt-2 text-xs leading-5 text-gray-500">Leia o cenário, escolha a resposta e confirme sua ciência. O registro compõe o histórico de desenvolvimento.</p></div></aside></div>
 </>;
}
