"use client";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { CheckCircle2, ChevronLeft, Clock3, FileText, Workflow, AlertTriangle, XCircle, ClipboardCheck, ArrowDown, Award } from "lucide-react";
import type { AccessibleResourcePayload, Aula } from "@/types";

const passos=["Solicitação recebida","Validar informações","Dados completos?","Verificar disponibilidade","Definir prioridade","Registrar agendamento","Comunicar envolvidos","Acompanhar deslocamento","Confirmar entrega","Encerrar e registrar desvios"];
const topicos=["O que é e quando acontece","Quem pode solicitar","Informações obrigatórias","Como validar a solicitação","Verificar disponibilidade","Definir prioridade","Registrar e comunicar","Acompanhar o frete","Confirmar conclusão","Registrar desvios"];
const checks=["Solicitante, origem e destino validados","Equipamento e prioridade conferidos","Disponibilidade da prancha verificada","Agendamento e horário registrados","Motorista e liderança comunicados","Entrega confirmada e desvio registrado"];
export default function AulaDetalhe(){const {id}=useParams<{id:string}>();const [aula,setAula]=useState<Aula|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");const [done,setDone]=useState(false),[marked,setMarked]=useState<boolean[]>(Array(6).fill(false));
useEffect(()=>{fetch("/api/aulas").then(async response=>{const payload=await response.json();if(!response.ok)throw new Error(payload.error);const match=(payload as AccessibleResourcePayload<Aula>).items.find(item=>item.id===id);if(!match)throw new Error("Aula não autorizada ou não encontrada.");setAula(match);}).catch(reason=>setError(reason instanceof Error?reason.message:"Não foi possível carregar a aula.")).finally(()=>setLoading(false));},[id]);
useEffect(()=>{setDone(localStorage.getItem(`capacita-aula-${id}`)==="completed");const saved=localStorage.getItem(`capacita-aula-checks-${id}`);if(saved)setMarked(JSON.parse(saved));},[id]);
function conclude(){if(!aula)return;setDone(true);localStorage.setItem(`capacita-aula-${id}`,"completed");localStorage.setItem("capacita-last-aula",JSON.stringify({nome:aula.titulo,mesa:aula.mesa,data:new Date().toLocaleDateString("pt-BR")}));}
function toggleCheck(index:number){setMarked(current=>{const next=current.map((v,i)=>i===index?!v:v);localStorage.setItem(`capacita-aula-checks-${id}`,JSON.stringify(next));return next;});}
if(loading)return <div className="card p-8 text-center text-sm text-gray-500">Carregando aula autorizada...</div>;if(error||!aula)return <div className="card p-8 text-center text-sm text-red-700">{error||"Aula não autorizada."}</div>;return <><Link href="/aulas" className="mb-5 inline-flex items-center gap-1 text-xs font-bold text-gray-500 hover:text-leaf"><ChevronLeft size={16}/>Voltar para aulas</Link><section className="card overflow-hidden"><div className="bg-forest p-7 text-white lg:p-9"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-blush px-3 py-1 text-[10px] font-bold text-forest">{aula.nivel}</span><span className="flex items-center gap-1 text-xs text-white/50"><Clock3 size={14}/>{aula.tempo} minutos</span></div><h1 className="mt-6 text-3xl font-bold">{aula.titulo}</h1><p className="mt-2 text-sm text-white/55">{aula.mesa}</p><p className="mt-6 max-w-3xl text-sm leading-6 text-white/75">{aula.objetivo}</p></div><div className="grid border-b border-line sm:grid-cols-2"><div className="flex gap-3 p-5 sm:border-r sm:border-line"><Workflow className="text-leaf"/><div><b className="text-sm">Fluxograma vinculado</b><p className="text-xs text-gray-400">Fluxo — {aula.titulo}</p></div></div><div className="flex gap-3 p-5"><FileText className="text-slate-700"/><div><b className="text-sm">IT vinculada</b><p className="text-xs text-gray-400">COA-IT-001 · Versão 3.0</p></div></div></div></section>
<div className="mt-5 grid gap-5 xl:grid-cols-[1fr_320px]"><div className="space-y-5"><section className="card p-6"><p className="eyebrow mb-2">Introdução</p><h2 className="text-xl font-bold">Por que este processo importa?</h2><p className="mt-3 text-sm leading-7 text-gray-600">O agendamento de frete de prancha conecta a necessidade do campo ao recurso correto. Uma validação bem feita reduz deslocamentos desnecessários, atrasos e perda de rastreabilidade.</p></section><section className="card p-6"><h2 className="font-bold">Conteúdo passo a passo</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{topicos.map((x,i)=><div key={x} className="flex gap-3 rounded-xl bg-mist p-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-forest text-[10px] font-bold text-white">{i+1}</span><span className="text-xs font-semibold">{x}</span></div>)}</div></section><section className="card p-6"><h2 className="mb-5 flex items-center gap-2 font-bold"><Workflow size={19} className="text-leaf"/>Fluxo operacional</h2><div className="flex flex-col items-center">{passos.map((x,i)=><div key={x} className="contents"><div className={`w-full max-w-lg rounded-xl border p-3 text-center text-xs font-bold ${i===2?"border-amber-300 bg-amber-50":"border-line bg-white"}`}>{x}</div>{i<passos.length-1&&<ArrowDown size={16} className="my-1.5 text-gray-300"/>}</div>)}</div></section><div className="grid gap-5 sm:grid-cols-2"><section className="card p-5"><h3 className="flex items-center gap-2 font-bold text-amber-700"><AlertTriangle size={18}/>Pontos críticos</h3><ul className="mt-4 space-y-2 text-xs leading-5 text-gray-600">{["Solicitação sem origem ou destino","Equipamento informado incorretamente","Prioridade não definida","Falta de comunicação","Desvio sem registro"].map(x=><li key={x}>• {x}</li>)}</ul></section><section className="card p-5"><h3 className="flex items-center gap-2 font-bold text-red-700"><XCircle size={18}/>Erros comuns</h3><ul className="mt-4 space-y-2 text-xs leading-5 text-gray-600">{["Agendar sem validar","Não registrar saída","Não acompanhar deslocamento","Não comunicar atraso","Não registrar cancelamento"].map(x=><li key={x}>• {x}</li>)}</ul></section></div><section className="card p-6"><h2 className="flex items-center gap-2 font-bold"><ClipboardCheck size={19} className="text-leaf"/>Checklist de fixação</h2><div className="mt-4 space-y-2">{checks.map((x,i)=><button onClick={()=>toggleCheck(i)} key={x} className={`flex w-full items-center gap-3 rounded-xl border p-3 text-left text-xs ${marked[i]?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-line"}`}><span className={`grid h-5 w-5 place-items-center rounded border ${marked[i]?"border-leaf bg-leaf text-white":"border-gray-300"}`}>{marked[i]&&<CheckCircle2 size={13}/>}</span>{x}</button>)}</div></section></div>
<aside><div className="card sticky top-24 p-5"><p className="eyebrow">Seu progresso</p><div className="mt-4 flex items-center justify-between text-xs"><span>Conteúdo da aula</span><b>{done?"100%":"70%"}</b></div><div className="mt-2 h-2 rounded bg-mist"><div className={`h-2 rounded bg-leaf transition-all ${done?"w-full":"w-[70%]"}`}/></div><div className="mt-5 space-y-3 text-xs">{["Introdução","Conteúdo","Fluxograma","Pontos críticos","Checklist","Simulado final"].map((x,i)=><div className="flex items-center gap-2" key={x}><CheckCircle2 size={15} className={i<4||done?"text-leaf":"text-gray-300"}/>{x}</div>)}</div>{done?<div className="mt-6 rounded-xl bg-emerald-50 p-4 text-center text-emerald-800"><Award className="mx-auto mb-2"/><b className="text-sm">Aula concluída!</b><p className="mt-1 text-[11px]">Registro disponível no histórico local.</p></div>:<button onClick={conclude} className="btn-primary mt-6 w-full">Concluir aula</button>}</div></aside></div></>;}
