"use client";
import { useEffect, useState } from "react";
import { PageHeader } from "@/components/layout/PageHeader";
import { Check, RotateCcw, ListChecks } from "lucide-react";
import type { AccessibleResourcePayload, Checklist } from "@/types";

export default function ChecklistsPage(){const [id,setId]=useState(""),[items,setItems]=useState<boolean[]>([]),[checklists,setChecklists]=useState<Checklist[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");const c=checklists.find(x=>x.id===id);useEffect(()=>{fetch("/api/checklists").then(async response=>{const payload=await response.json();if(!response.ok)throw new Error(payload.error);const data=(payload as AccessibleResourcePayload<Checklist>).items;setChecklists(data);setId(data[0]?.id||"");}).catch(reason=>setError(reason instanceof Error?reason.message:"Não foi possível carregar os checklists.")).finally(()=>setLoading(false));},[]);useEffect(()=>{if(!c)return;const saved=localStorage.getItem(`capacita-checklist-${id}`);setItems(saved?JSON.parse(saved):Array(c.itens.length).fill(false));},[c,id]);const total=items.filter(Boolean).length,pct=Math.round(total/items.length*100)||0;
function toggle(index:number){if(!c)return;setItems(current=>{const next=current.map((value,i)=>i===index?!value:value);localStorage.setItem(`capacita-checklist-${id}`,JSON.stringify(next));if(next.every(Boolean))localStorage.setItem("capacita-last-checklist",JSON.stringify({nome:c.nome,mesa:c.mesa,data:new Date().toLocaleDateString("pt-BR")}));return next;});}
if(loading)return <div className="card p-8 text-center text-sm text-gray-500">Carregando checklists autorizados...</div>;if(error||!c)return <div className="card p-8 text-center text-sm text-red-700">{error||"Nenhum checklist disponível."}</div>;
return <><PageHeader eyebrow="Apoio à execução" title="Checklists" description="Conferências rápidas para transformar o procedimento em prática consistente."/><div className="grid gap-5 xl:grid-cols-[300px_1fr]"><aside className="card h-fit p-3">{checklists.map(x=><button onClick={()=>setId(x.id)} key={x.id} className={`mb-1 flex w-full items-center gap-3 rounded-xl p-3 text-left text-xs ${id===x.id?"bg-forest font-bold text-white":"hover:bg-mist"}`}><ListChecks size={16}/><span>{x.nome.replace("Checklist — ","")}</span></button>)}</aside><section className="card overflow-hidden"><div className="border-b border-line p-6"><p className="eyebrow">{c.mesa}</p><h2 className="mt-2 text-xl font-bold">{c.nome}</h2><div className="mt-5 flex items-center gap-3"><div className="h-2 flex-1 overflow-hidden rounded-full bg-mist"><div className="h-full rounded-full bg-leaf transition-all" style={{width:`${pct}%`}}/></div><b className="text-xs text-leaf">{pct}%</b></div></div><div className="space-y-2 p-6">{c.itens.map((x,i)=><button key={x} onClick={()=>toggle(i)} className={`flex w-full items-center gap-3 rounded-xl border p-3.5 text-left text-sm transition ${items[i]?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-line hover:border-leaf/50"}`}><span className={`grid h-6 w-6 shrink-0 place-items-center rounded-md border ${items[i]?"border-leaf bg-leaf text-white":"border-gray-300 bg-white"}`}>{items[i]&&<Check size={15}/>}</span><span className={items[i]?"line-through opacity-70":""}>{x}</span></button>)}{pct===100&&<div className="flex items-center gap-3 rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-800"><Check/>Checklist concluído</div>}<div className="flex flex-col gap-3 pt-4 sm:flex-row"><button onClick={()=>{const empty=Array(c.itens.length).fill(false);setItems(empty);localStorage.setItem(`capacita-checklist-${id}`,JSON.stringify(empty));}} className="btn-secondary"><RotateCcw size={15}/>Limpar</button><button disabled={pct<100} className="btn-primary flex-1">Concluir checklist</button></div></div></section></div></>;}
