"use client";
import { useEffect, useState } from "react";
import { PageHeader } from "@/components/layout/PageHeader";
import { StatusBadge } from "@/components/badges/StatusBadge";
import { FileText, Eye, X, CalendarDays, Layers3, Search } from "lucide-react";
import type { AccessibleResourcePayload, ITProcedimento } from "@/types";

export default function ItsPage(){const [open,setOpen]=useState<string|null>(null),[q,setQ]=useState("");const [items,setItems]=useState<ITProcedimento[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");useEffect(()=>{fetch("/api/its").then(async response=>{const payload=await response.json();if(!response.ok)throw new Error(payload.error);setItems((payload as AccessibleResourcePayload<ITProcedimento>).items);}).catch(reason=>setError(reason instanceof Error?reason.message:"Não foi possível carregar as ITs.")).finally(()=>setLoading(false));},[]);const data=items.filter(x=>x.nome.toLowerCase().includes(q.toLowerCase()));const selected=items.find(x=>x.id===open);
if(loading)return <div className="card p-8 text-center text-sm text-gray-500">Carregando ITs autorizadas...</div>;if(error)return <div className="card p-8 text-center text-sm text-red-700">{error}</div>;
return <><PageHeader eyebrow="Fonte oficial" title="Biblioteca de ITs" description="Procedimentos vigentes, organizados por mesa e preparados para futura sincronização com o SharePoint." action={<button className="btn-secondary"><Layers3 size={16}/>15 documentos ativos</button>}/><div className="card mb-5 p-3"><div className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input value={q} onChange={e=>setQ(e.target.value)} className="field py-2.5 pl-9" placeholder="Buscar por nome ou código..."/></div></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.map(x=><article key={x.id} className="card p-5"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl bg-slate-100 text-slate-700"><FileText size={20}/></span><StatusBadge status={x.status}/></div><p className="mt-5 text-[10px] font-bold uppercase tracking-wider text-leaf">{x.mesa}</p><h2 className="mt-2 min-h-10 text-sm font-bold">{x.nome}</h2><p className="mt-2 line-clamp-2 text-xs leading-5 text-gray-500">{x.resumo}</p><div className="mt-5 flex items-center gap-4 border-t border-line pt-4 text-[11px] text-gray-400"><span>{x.codigo}</span><span>v{x.versao}</span><span className="ml-auto flex items-center gap-1"><CalendarDays size={12}/>{x.atualizacao}</span></div><button onClick={()=>setOpen(x.id)} className="btn-secondary mt-4 w-full"><Eye size={15}/>Visualizar</button></article>)}</div>
{selected&&<div className="fixed inset-0 z-[60] grid place-items-center bg-black/50 p-4"><div className="card max-h-[90vh] w-full max-w-2xl overflow-y-auto p-6"><div className="flex justify-between"><span className="grid h-12 w-12 place-items-center rounded-xl bg-slate-100 text-slate-700"><FileText/></span><button onClick={()=>setOpen(null)}><X/></button></div><p className="eyebrow mt-6">{selected.codigo} · Versão {selected.versao}</p><h2 className="mt-2 text-2xl font-bold">{selected.nome}</h2><p className="mt-2 text-xs text-gray-400">{selected.mesa} · Atualizada em {selected.atualizacao}</p><div className="mt-6 rounded-xl bg-mist p-5 text-sm leading-7 text-gray-600">{selected.resumo}<br/><br/>Esta visualização representa o documento oficial. Na arquitetura futura, o arquivo e o controle de versão serão originados da Biblioteca de Documentos do SharePoint.</div><button onClick={()=>setOpen(null)} className="btn-primary mt-6 w-full">Marcar leitura como concluída</button></div></div>}</>;}
