"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { PageHeader } from "@/components/layout/PageHeader";
import { StatusBadge } from "@/components/badges/StatusBadge";
import { BookOpen, Clock3, ArrowRight, Search } from "lucide-react";
import type { AccessibleResourcePayload, Aula } from "@/types";

export default function AulasPage(){const [mesa,setMesa]=useState("Todas"),[q,setQ]=useState("");const [items,setItems]=useState<Aula[]>([]),[mesas,setMesas]=useState<string[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");useEffect(()=>{fetch("/api/aulas").then(async response=>{const payload=await response.json();if(!response.ok)throw new Error(payload.error);const data=payload as AccessibleResourcePayload<Aula>;setItems(data.items);setMesas(data.mesas);}).catch(reason=>setError(reason instanceof Error?reason.message:"Não foi possível carregar as aulas.")).finally(()=>setLoading(false));},[]);const data=items.filter(a=>(mesa==="Todas"||a.mesa===mesa)&&a.titulo.toLowerCase().includes(q.toLowerCase()));
if(loading)return <div className="card p-8 text-center text-sm text-gray-500">Carregando aulas autorizadas...</div>;if(error)return <div className="card p-8 text-center text-sm text-red-700">{error}</div>;
return <><PageHeader eyebrow="Aprendizado operacional" title="Aulas Operacionais" description="Conteúdos curtos que conectam o fluxo, a regra oficial e a prática do dia a dia."/><div className="card mb-5 flex flex-col gap-3 p-3 sm:flex-row"><div className="relative flex-1"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input className="field py-2.5 pl-9" value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar uma aula..."/></div><select className="field sm:w-64" value={mesa} onChange={e=>setMesa(e.target.value)}><option>Todas</option>{mesas.map(name=><option key={name}>{name}</option>)}</select></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.map(a=><Link href={`/aulas/${a.id}`} key={a.id} className="card group overflow-hidden transition hover:-translate-y-0.5 hover:border-leaf/40"><div className="flex items-center justify-between border-b border-line bg-mist/60 p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white text-leaf shadow-sm"><BookOpen size={19}/></span><StatusBadge status={a.status}/></div><div className="p-5"><small className="text-[10px] font-bold uppercase tracking-wider text-leaf">{a.mesa}</small><h2 className="mt-2 min-h-11 font-bold leading-5">{a.titulo}</h2><p className="mt-2 line-clamp-2 text-xs leading-5 text-gray-500">{a.objetivo}</p><div className="mt-5 flex items-center justify-between border-t border-line pt-4 text-xs"><span className="flex items-center gap-1 text-gray-400"><Clock3 size={14}/>{a.tempo} min · {a.nivel}</span><span className="flex items-center gap-1 font-bold text-leaf">{a.status==="Em andamento"?"Continuar aula":a.status==="Concluído"?"Revisar aula":"Iniciar aula"}<ArrowRight size={15}/></span></div></div></Link>)}</div></>;}
